name: CI

on:
  push:

jobs:
  lint:
    name: "Lint Code"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Set-up Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - run: pnpm install
      - run: pnpm run lint