name: CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  lint:
    name: "Lint Code"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Set-up Node
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm install
      - run: pnpm run lint