name: Publish Packages

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-package:
    name: "Publish to GitHub Packages"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Set-up Node
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm install
      - run: pnpm run publish --tag=$(echo ${GITHUB_REF_NAME:1})
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}