name: Publish Packages

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: read

jobs:
  release-npm:
    name: "Release NPM"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ vars.PNPM_VERSION }}
      - name: Set-up Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ vars.NODEJS_VERSION }}
          cache: "pnpm"
          registry-url: https://registry.npmjs.org
      - name: Sync package.json version with tag
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "Setting version to $VERSION"
          pnpm version $VERSION --no-git-tag-version
      - name: Install Dependencies
        run: pnpm install
      - name: Build Package
        run: |
          pnpm run build
          pnpm pack
      - name: Publish to npmjs
        run: pnpm run release:npm
  release-github:
    name: "Release Github Packages"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ vars.PNPM_VERSION }}
      - name: Set-up Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ vars.NODEJS_VERSION }}
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@zwolly"
      - name: Sync package.json version with tag
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "Setting version to $VERSION"
          pnpm version $VERSION --no-git-tag-version
      - name: Install Dependencies
        run: pnpm install
      - name: Build Package
        run: |
          pnpm run build
          pnpm pack
      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run release:github
